#based on mlperf Dockerfile
#to build, sudo docker build . -t mlperf
#to run, cd CapsuleNet-Keras; docker run -v /path/of/CapsNet-Keras/:/w --runtime=nvidia -t -i mlperf
#insider docker, cd /w; python3 capsulenet.py

FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04


WORKDIR /research

RUN apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    python \
    python-pip


ENV HOME /research
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH


RUN apt-get install -y python-setuptools

RUN apt-get install -y python-pip python3-pip virtualenv htop
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade numpy scipy sklearn
RUN pip3 install --upgrade tf-nightly-gpu


# Mount data into the docker
ADD . /research/resnet


WORKDIR /research/resnet
RUN pip3 install -r official/requirements.txt

RUN  pip install keras
RUN pip install numpy
RUN  pip3 install matplotlib
RUN  apt install -y python3-tk
RUN  pip install pillow

ENTRYPOINT ["/bin/bash"]
